### ISSUE TITLE
[blemesh] CLI reset does not seems to clear all the Mesh credentials

### ISSUE THREAD

**Issue by rymanluk** [apache/mynewt-nimble#557]
How to reproduce:
1) Configure mesh node to use FCB and Settings
2) Provision
3) Call 'reset' command from mesh shell
4) Restart board and call 'init' in `mesh` shell

Expected: mesh starts advertising as non provisioned node

**Comment by michal-narajowski** [comment]
After investigating this issue I found that the problem was caused by misleading logs and is **not a bug**. FCB does not overwrite values that were previously written. Instead, it writes a new record with a different value (in this case a null value). So when restoring data from flash it looks like the keys are restored and then cleared, because this is the order in which those operations were stored. It can be a bit misleading at first glance.
