### ISSUE TITLE
Move BLE sample apps from core to nimble repo

### ISSUE THREAD

**Issue by sjanc** [apache/mynewt-nimble#80]
We could have sample apps in nimble instead of core repo.
Since sample applications are OS specific we probably need to keep them per os eg  apps/mynewt/ apps/freertos etc.

**Comment by turon** [comment]
Cloning the sample apps for each platform isn't really scalable.  The btshell app for example would require copying of a lot of code.  Better would be to make the sample apps use NPL so they are portable across the various platforms.

**Comment by andrzej-kaczmarek** [comment]
apps like `btshell` are not really portable since they have dependencies on `mynewt-core` (e.g. console, shell) which are out of scope of NPL.

apps like `bleprph` or `blecent` (or we can add new apps) could be refactored in a way that it is easy to grab ble-related code and use in port for other OS easily. we may also add an ootb configuration to build on Linux in addition to Mynewt.

but in general I agree we can keep apps for NimBLE in `mynewt-nimble` instead of `mynewt-core` to make maintenance easier.

**Comment by sjanc** [comment]
note that sample application will be OS specific even if it will reside in nimble repo

**Comment by rymanluk** [comment]
Completed
